### ISSUE TITLE
Enable pyup.io for taking care of dependencies

### ISSUE THREAD

**Issue by davehunt** [mozilla/treeherder-tests#101]
We want to enable [pyup.io](https://pyup.io/) for our projects to take care of automating the updates to our dependencies. Here's what's needed:

- [x] Move dependencies out of `tox.ini` and into requirements files. See https://github.com/mozilla/PyPOM/commit/ad21988d0364843808c07f3aaa656c6c16b971b2 for an example of this.
- [x] Add repository to pyup.io (@davehunt can take care of this once the above is merged).
- [x] Add pyup.io badges for updates and python 3 readyness. See https://github.com/mozilla/PyPOM/commit/931c41b964f1c9950983c078d0583ef708ac8af9 for an example of this.
- [x] Remove requires.io badge from README.
- [x] Remove repository from [requires.io](https://requires.io/) (@davehunt can take care of this once pyup.io is working)

**Comment by jayfk** [comment]
If there are any questions, just @mention me here and I'll jump in.

**Comment by davehunt** [comment]
First part is done, I've configured pyup.io for the repository, and an initial pull request has been opened. Once #103 has been reviewed and merged we can add the pyup.io badges and remove requires.io.

**Comment by stephendonner** [comment]
@davehunt https://github.com/mozilla/treeherder-tests/pull/103 is merged; we're good to go with adding badges and removing requires.io integration - thanks!

**Comment by davehunt** [comment]
All done, thanks @rbillings!
