### ISSUE TITLE
Add exception as a failure type for failure navigation

### ISSUE THREAD

**Issue by tojonmz** [mozilla/treeherder-tests#15]
We currently look for jobstatus [testfailed and busted](https://github.com/mozilla/treeherder-tests/blob/master/tests/test_unclassified_job.py#L27), but there was the rare case like one day last week where virtually all the failures in mozilla-inbound were infrastructure exceptions. So I'll add that value also.

All status's can also be found on Help in the notation table, and here
https://github.com/mozilla/treeherder/blob/725dd2b500f4630137f596b3400bcce45d38a5da/ui/js/providers.js#L19

'Black' aka. 'unknown' is another failure type, but I haven't seen that in over 1.5yrs of treeherder so I think it's reasonable to omit that for now.

I'll open a PR shortly. :)

**Comment by davehunt** [comment]
This was fixed in https://github.com/mozilla/treeherder-tests/commit/1db83e8abdfcc339f9327ccc5f5039685d9242b0
