### ISSUE TITLE
Remove test classes

### ISSUE THREAD

**Issue by davehunt** [mozilla/treeherder-tests#34]
In pytest it's not necessary to have your tests inside classes, so let's get rid of them. This means removing the class definition, removing the indentation of the test functions, removing the `self` argument from the test functions, and separating the test functions with two blank lines.

For example:
```python
class TestLogin():

    @pytest.mark.nondestructive
    def test_that_a_new_user_can_login(self, base_url, selenium, new_user):
        page = TreeherderPage(base_url, selenium).open()
        page.header.login(new_user['email'], new_user['password'])
        assert page.header.is_user_logged_in
```

Would become:
```python
@pytest.mark.nondestructive
def test_that_a_new_user_can_login(base_url, selenium, new_user):
    page = TreeherderPage(base_url, selenium).open()
    page.header.login(new_user['email'], new_user['password'])
    assert page.header.is_user_logged_in
```

**Comment by bebef1987** [comment]
Steeling this issue

**Comment by davehunt** [comment]
Hey Bebe, could you leave this issue for Outreachy applicants?

Thanks,
Dave Hunt

**Comment by AleenaCodes** [comment]
Hi @davehunt I'm looking to apply for the Outreachy program for this summer, is this a good patch to work on? (Or is there another one you'd recommend?)

Thanks

**Comment by davehunt** [comment]
Hi @AleenaCodes the work has already been done in #36. Thank you for your interest though, perhaps you can find another tasks to work on here: https://github.com/davehunt/pytest-html#application-contributions

**Comment by rbillings** [comment]
PR was merged, closing this as fixed.
