### ISSUE TITLE
Test Case - View a single resultset

### ISSUE THREAD

**Issue by tojon** [mozilla/treeherder-tests#4]
This test corresponds with Moztrap test case [15828](https://moztrap.mozilla.org/manage/case/15828/).

1. Load Treeherder and click on the 'Date' on the left side of any resultset.

> Only that resultset should load, with an accompanying URL param "&revision=(SHA)"

So we can check to ensure there is only one resultset in the DOM after the load, it contains a matching date, and in doing so validate the single resultset load worked.

The only scenario where this would be data dependent would be if the repo only contains one resultset to begin with - but with mozilla-inbound we can be confident that won't be the case.

**Comment by davehunt** [comment]
Landed in https://github.com/mozilla/treeherder-tests/commit/ad19cac05d0c29e34e2edaee0e306558c3b3c750.
