### ISSUE TITLE
Test: Test the Filters Panel

### ISSUE THREAD

**Issue by rbillings** [mozilla/treeherder-tests#50]
Create two tests for the Filters panel.

Edit filter test
1) Open treeherder
2) Open Filters panel by clicking nav button
3) Edit filter to only show one type of failure

Verify that results update correctly by selecting the next unclassified failure [existing test], viewing Job Details and making sure that the Result matches the applied filter.

Reset filter test
1) After the steps above, click the "reset" button

Verify that the default checkboxes are selected.

**Comment by MichalTHEDUDE** [comment]
Could you please assign me for this one?

**Comment by davehunt** [comment]
@MichalTHEDUDE I've invited you as a collaborator for this repository. Once you've accepted we can assign the issue to you. 😄

**Comment by rbillings** [comment]
This was completed in #81 !
