### ISSUE TITLE
Test: Filter by job keywords

### ISSUE THREAD

**Issue by rbillings** [mozilla/treeherder-tests#52]
Create a test for filtering jobs by keywords.

1) Open treeherder
2) Select any job
3) Within the job details panel on the left hand side, click any of the keyword links next to "Job"

Verify that list of jobs updates to display only jobs with the selected keyword[s]. Verify that filter displays in the header.

**Comment by MichalTHEDUDE** [comment]
Hi Guys! I can work on this one!

- By 'keyword links next to "Job"' you mean like: 'linux opt', 'linux x64 pgo' or 'Windows XP opt' right?
- By 'Verify that filter displays in the header' you mean in the page URL after clicking?

**Comment by rbillings** [comment]
Next to "Job" in the attached screenshot is a link with keywords. A better verification would be that the filtered jobs match the keywords from the link.

ex of link: https://treeherder.allizom.org/#/jobs?repo=mozilla-inbound&selectedJob=34980321&filter-searchStr=Linux%20x64%20asan%20Reftests%20executed%20by%20TaskCluster%20desktop-test-linux64-asan%2Fopt-reftest-no-accel-4%20tc-R(Ru4)

<img width="346" alt="screen shot 2016-10-07 at 10 09 24 am" src="https://cloud.githubusercontent.com/assets/737878/19198882/2e2fe0cc-8c76-11e6-8984-cb211225b113.png">

**Comment by rbillings** [comment]
This was done.
