### ISSUE TITLE
Test: Filter jobs by email

### ISSUE THREAD

**Issue by rbillings** [mozilla/treeherder-tests#54]
Create two tests that add and remove filters by email address.

Filter by Email address
1) Open Treeherder page
2) Click a random email address from any of the jobs listed

Verify that jobs list is updated to only display jobs by selected author.

Remove email address filter
3) Click active repo name [default is mozilla-inbound]

Verify that jobs list is updated to display jobs by all authors.

**Comment by MichalTHEDUDE** [comment]
I can work on this one :).

**Comment by rbillings** [comment]
Great, thanks @MichalTHEDUDE

**Comment by rbillings** [comment]
This was done.
