### ISSUE TITLE
Test: Keyboard shortcuts

### ISSUE THREAD

**Issue by rbillings** [mozilla/treeherder-tests#57]
There are quite a few keyboard shortcuts described here: https://treeherder.allizom.org/userguide.html

Create a test verifying that each shortcut works correctly. The "n" and spacebar keyboard shortcuts already exist and can be used as an example.

**Comment by rbillings** [comment]
Next step: Check if there is coverage for this in the unit tests. If not, determine which keyboard shortcuts are not data dependent.

**Comment by MichalTHEDUDE** [comment]
I can start working on this issue :)

**Comment by rbillings** [comment]
This is completed for now- there is always room for future improvements.
