### ISSUE TITLE
Test: Move to top or bottom of range

### ISSUE THREAD

**Issue by rbillings** [mozilla/treeherder-tests#63]
Create a test to move a resultset to the top or bottom of range.

1) Open Treeherder
2) Next to any resultset open dropdown arrow, select "Set as top of range"

Verify resultset is moved to top of the page, url contains "&tochange="

3) Open dropdown arrow on resultset, select "Set as bottom of range"

Verify resultset is moved to the bottom of the page, url contains "fromchange="

**Comment by terrameijar** [comment]
Hi @rbillings I would like to help with these tests, but I'm not sure where to start, I don't quite understand what treeherder is or does. Can you point me in the right direction?

**Comment by rbillings** [comment]
Hi @terrameijar - Treeherder is a reporting dashboard for Mozilla checkins.
You can work with the staging environment here: https://treeherder.allizom.org/#/jobs?repo=mozilla-inbound
The main repo is at: https://github.com/mozilla/treeherder
Let me know if you have any more questions!

**Comment by terrameijar** [comment]
ok, thanks, I'll try this issue

**Comment by rbillings** [comment]
great!

**Comment by rbillings** [comment]
Closed.
