### ISSUE TITLE
Test: Job status buttons

### ISSUE THREAD

**Issue by rbillings** [mozilla/treeherder-tests#65]
This test verifies the job status buttons in the nav bar.

1) Open Treeherder
2) Click the red button for: "failures" in the status bar
Verify red circle does not have dot in the middle, verify failed jobs do not display
3) Repeat for success, retry, usercancel, and in progress buttons
Verify circles do not have dot in the middle, jobs do not display
4) Click the light blue button for: "coalesced"
Verify button does have dot in the middle, jobs do display
5) Click the red button
Verify dot appears, jobs return to display

**Comment by MichalTHEDUDE** [comment]
Hi,

I have checked job status according to your instructions.
Everything seems to be fine (as you described).

Does red button include 'exceptions'? Because I've noticed them displaying with failures.

**Comment by rbillings** [comment]
@MichalTHEDUDE - this is an issue to create an automated test to follow the steps above. Yes, that does include exceptions, failures, and busted status. Glad to know it's still working as expected.

**Comment by MichalTHEDUDE** [comment]
Quick question.
Am I understand correctly that this Issue require to write a CSS Selectors and functions in pages/treeherder.py and also creating new .py script in tests folder? Similar to #69 ?

**Comment by rbillings** [comment]
Yes, this test will be written using Python/Selenium and the methods should be written in the treeherder.py. This test is taken, but if you're up for it there are other open tests waiting to be written.
