### ISSUE TITLE
Test Case - Pin a job

### ISSUE THREAD

**Issue by tojon** [mozilla/treeherder-tests#8]
This test corresponds with Moztrap test case [15814](https://moztrap.mozilla.org/manage/case/15814/).

1. Select a job, and click the 'pin' button in the lower navbar.
> The selected job is pinned.

2. Select another job, and hit [spacebar]
> The selected job is pinned.

3. Pinboard > Right hand menu dropdown > Clear all
> Both jobs are removed from the pinboard.

**Comment by rbillings** [comment]
This test cannot be implemented until issue #5 has been completed.
