### ISSUE TITLE
Switch over to using Tox

### ISSUE THREAD

**Issue by stephendonner** [mozilla/treeherder-tests#85]
bidpom and fxapom have already switched, and this is now being tracked in our Baseline: https://wiki.mozilla.org/TestEngineering/Web/Automation/Baseline

Let's switch over to Tox: https://tox.readthedocs.io/en/latest/

**Comment by stephendonner** [comment]
@rbillings @MichalTHEDUDE if either of you would like to take this, I'd be happy to review it.  If neither of you want it, I'd also be happy to take it.

Just don't want to steal away an opportunity from either of you!

**Comment by MichalTHEDUDE** [comment]
I can look at it. I will have some time after 26th of Sep. (I'm a little bit busy right now).
Would it be okay?

**Comment by rbillings** [comment]
@MichalTHEDUDE - if this is still open on the 26th you'd be more than welcome. That's my way of saying we won't save it, but anything that is open is there to be looked at! If this is closed, something else will surely need attention. :)

**Comment by MichalTHEDUDE** [comment]
@stephendonner please check #87 :)

**Comment by davehunt** [comment]
Fixed in https://github.com/mozilla/treeherder-tests/commit/c288d7a24d24619da76a7e3c6efa2d4a664cab21
