### ISSUE TITLE
Test Case - Initial page load

### ISSUE THREAD

**Issue by tojon** [mozilla/treeherder-tests#9]
This test corresponds with Moztrap test case [15811](https://moztrap.mozilla.org/manage/case/15811/).

1. Load Treeherder from your specified instance: local, [stage](https://treeherder.allizom.org), or [production](https://treeherder.mozilla.org)
> Page loads displaying at least one resultset pushed to mozilla-inbound.

2. Treeherder logo > Perfherder
> Perfherder loads displaying its initial Graph page.

3. Perfherder logo > Treeherder
> Treeherder loads again, displaying resultsets per step 1.

**Comment by rbillings** [comment]
Completed
